"""initial schema

Revision ID: 37de97fc8022
Revises: 
Create Date: 2026-06-21 19:42:07.609299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37de97fc8022'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint("kind IN ('status_zakup','status_sdelki')", name='dict_kind_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='dict_kind_value_unique')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('is_curator', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('global_role', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('must_change_password', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("account_type IN ('department','global')", name='user_account_type_check'),
    sa.CheckConstraint("department IN ('Комплектация','Закупки','Сопровождение')", name='user_department_check'),
    sa.CheckConstraint("global_role IN ('Админ','Руководитель')", name='user_global_role_check'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_kind', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_kind', 'entity_id'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_kind', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("target_kind IN ('parent','tender','procedure')", name='comment_target_kind_check'),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_target', 'comment', ['target_kind', 'target_id'], unique=False)
    op.create_table('parent_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('mtr', sa.Text(), nullable=True),
    sa.Column('srok', sa.Text(), nullable=True),
    sa.Column('zagruzka', sa.Text(), server_default=sa.text("(date('now'))"), nullable=False),
    sa.Column('sostavitel', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('dept', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'awaiting'"), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("status IN ('awaiting','cancelled')", name='parent_request_status_check'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_parent_status', 'parent_request', ['status'], unique=False)
    op.create_table('requested_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('gost_tu', sa.Text(), nullable=True),
    sa.Column('doc_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reqpos_parent', 'requested_position', ['parent_id'], unique=False)
    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    op.create_index('ix_tender_parent', 'tender', ['parent_id'], unique=False)
    op.create_table('procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proc', sa.Text(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('fio_zakupshchik', sa.Text(), nullable=True),
    sa.Column('fio_dogovornik', sa.Text(), nullable=True),
    sa.Column('mtr', sa.Text(), nullable=True),
    sa.Column('pub_start', sa.Text(), nullable=True),
    sa.Column('pub_end', sa.Text(), nullable=True),
    sa.Column('contract', sa.Text(), nullable=True),
    sa.Column('contract_sum', sa.Integer(), nullable=True),
    sa.Column('block', sa.Text(), server_default=sa.text("'zakupka'"), nullable=False),
    sa.Column('block_entered_at', sa.Text(), nullable=True),
    sa.Column('status_zakup', sa.Text(), nullable=True),
    sa.Column('status_postavki', sa.Text(), nullable=True),
    sa.Column('status_sdelki', sa.Text(), nullable=True),
    sa.Column('srok_dd', sa.Text(), nullable=True),
    sa.Column('plan_date', sa.Text(), nullable=True),
    sa.Column('fakt_date', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("block IN ('zakupka','soprovozhdenie')", name='procedure_block_check'),
    sa.CheckConstraint("status_postavki IN ('Новая','В производстве','В поставке','Частично поставлено','Поставлено','Отменена')", name='procedure_status_postavki_check'),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proc')
    )
    op.create_index('ix_proc_block', 'procedure', ['block'], unique=False)
    op.create_index('ix_proc_supplier', 'procedure', ['supplier'], unique=False)
    op.create_index('ix_proc_tender', 'procedure', ['tender_id'], unique=False)
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'transit'"), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('eta', sa.Text(), nullable=True),
    sa.Column('doc_ttn', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('doc_m15', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('doc_upd', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('doc_sert', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.CheckConstraint("status IN ('transit','done')", name='delivery_status_check'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_proc', 'delivery', ['procedure_id'], unique=False)
    op.create_table('procedure_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('gost_tu', sa.Text(), nullable=True),
    sa.Column('doc_code', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['requested_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_procpos_delivery', 'procedure_position', ['delivery_id'], unique=False)
    op.create_index('ix_procpos_proc', 'procedure_position', ['procedure_id'], unique=False)
    op.create_index('ix_procpos_source', 'procedure_position', ['source_id'], unique=False)
    op.create_table('upd_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upd', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('ext_source', sa.Text(), nullable=True),
    sa.Column('ext_id', sa.Text(), nullable=True),
    sa.Column('request_label', sa.Text(), nullable=True),
    sa.Column('supplier', sa.Text(), nullable=True),
    sa.Column('contract', sa.Text(), nullable=True),
    sa.Column('zrds', sa.Text(), nullable=True),
    sa.Column('srok', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('pay_status', sa.Text(), server_default=sa.text("'await'"), nullable=False),
    sa.Column('pay_date', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("origin IN ('delivery','manual','external')", name='upd_payment_origin_check'),
    sa.CheckConstraint("pay_status IN ('await','paid')", name='upd_payment_pay_status_check'),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upd_delivery', 'upd_payment', ['delivery_id'], unique=False)
    op.create_index('ix_upd_paystatus', 'upd_payment', ['pay_status'], unique=False)
    op.create_table('upd_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upd_payment_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upd_payment_id'], ['upd_payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_updpos_upd', 'upd_position', ['upd_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_updpos_upd', table_name='upd_position')
    op.drop_table('upd_position')
    op.drop_index('ix_upd_paystatus', table_name='upd_payment')
    op.drop_index('ix_upd_delivery', table_name='upd_payment')
    op.drop_table('upd_payment')
    op.drop_index('ix_procpos_source', table_name='procedure_position')
    op.drop_index('ix_procpos_proc', table_name='procedure_position')
    op.drop_index('ix_procpos_delivery', table_name='procedure_position')
    op.drop_table('procedure_position')
    op.drop_index('ix_delivery_proc', table_name='delivery')
    op.drop_table('delivery')
    op.drop_index('ix_proc_tender', table_name='procedure')
    op.drop_index('ix_proc_supplier', table_name='procedure')
    op.drop_index('ix_proc_block', table_name='procedure')
    op.drop_table('procedure')
    op.drop_index('ix_tender_parent', table_name='tender')
    op.drop_table('tender')
    op.drop_index('ix_reqpos_parent', table_name='requested_position')
    op.drop_table('requested_position')
    op.drop_index('ix_parent_status', table_name='parent_request')
    op.drop_table('parent_request')
    op.drop_index('ix_comment_target', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_table('dict')
    # ### end Alembic commands ###
